# Generated by Django 5.1.7 on 2025-04-18 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ierarhie_lectie_flashcard_reviewstate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
